### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [playproject-io-archive/solverify#1]
## `@todo`
* [ ] make solverify concept
* [ ] ping @serapath and ask for more details on how to **manually** verify contracts
* [ ] write verify solidity source code module

---
